"""create links and link_stats table

Revision ID: 111e0f796046
Revises: 
Create Date: 2025-12-13 15:25:11.150650

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '111e0f796046'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('short_code', sa.String(length=8), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_short_code'), 'link', ['short_code'], unique=True)
    op.create_table('link_stats',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.BigInteger(), nullable=False),
    sa.Column('last_click_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_stats_link_id'), 'link_stats', ['link_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_stats_link_id'), table_name='link_stats')
    op.drop_table('link_stats')
    op.drop_index(op.f('ix_link_short_code'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
