server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=30s;
    resolver_timeout 5s;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    client_max_body_size 1M;

    location ~ "^/([a-zA-Z0-9]{8})$" {
        set $short_code $1;
        set $backend_url http://url-shorter-backend:6749/api/v1/links/$short_code;
        proxy_pass $backend_url;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        set $backend_url http://url-shorter-backend:6749;
        proxy_pass $backend_url;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
